### ISSUE TITLE
Init

### ISSUE THREAD

**Issue by chinalwb** [chinalwb/slidetoconfirm#1]
![Sharp corners](https://user-images.githubusercontent.com/1758864/78349273-efce9b00-75d5-11ea-9a10-8022db9ade5a.png)

![Round corners](https://user-images.githubusercontent.com/1758864/78349279-f230f500-75d5-11ea-9679-d3f400cd7135.png)

![Circle](https://user-images.githubusercontent.com/1758864/78349282-f52be580-75d5-11ea-8ca7-26531129b171.png)

![UI_4](https://user-images.githubusercontent.com/1758864/78350196-5dc79200-75d7-11ea-9971-6f0a0799d21b.png)

![UI_5](https://user-images.githubusercontent.com/1758864/78350204-6029ec00-75d7-11ea-8f1c-4da0558f5337.png)

![samples](https://user-images.githubusercontent.com/1758864/86143658-4b51eb80-bb27-11ea-9873-e3d00209ce6d.gif)

**Comment by GodFan4** [comment]
滑动确认后该如何还原呢，没有找到对应的方法

**Comment by chinalwb** [comment]
@GodFan4  你是说 确认完毕之后 再把状态还原吗？ 如果是这个意思的话 那是不支持的。

这个控件目前分三个状态
1. 初始状态， 就是上面图中所示
2. 拖动状态，就是滑块划过的样式
3. 完毕状态，就是滑动到最右面，确认完之后的状态

1 <--> 2 --> 3
1 和 2 之间可以切换状态，2 到 3 是单向的。

**Comment by GodFan4** [comment]
嗯嗯，希望后期如果能加上状态还原就好了。
使用场景：滑动确认后，进行网络请求，若请求结果不成功，就需要还原

**Comment by chinalwb** [comment]
有道理 我会加上。 等我通知 嘿嘿

**Comment by chinalwb** [comment]
对还原动画有要求吗

**Comment by GodFan4** [comment]
谢谢，没有特殊要求，只要合适就行

**Comment by chinalwb** [comment]
@GodFan4  试试 `SlideToConfirm#reset()`, 在 `1.0.2` 版本中。因为没想到合适的动画，暂时没加。

**Comment by GodFan4** [comment]
已经测试了，可以，满足逻辑处理就行，动画可有可无
