### ISSUE TITLE
圆形效果

### ISSUE THREAD

**Issue by mallxiaodoudou** [chinalwb/slidetoconfirm#3]
老哥，你demo效果图的 第三个第四个那种圆形效果怎么做？ 好像没有这样的属性设置 设置圆角属性也是设置的滑块的圆角 底部背景的圆角无法设置

**Comment by mallxiaodoudou** [comment]
使用这种bg.setCornerRadii() 方式不好画出一个圆形 如果直接放圆形图片 滑动的时候这个滑块的两边圆角就对不上，最好是属性设置圆角为圆形的

**Comment by chinalwb** [comment]
配置名称 | 描述 | 示例参数值
-- | -- | --
border_radius | 整个控件边框的圆角半径 | 0dp / 2dp / xx dp



试过这个了吗

**Comment by mallxiaodoudou** [comment]
试了 椭圆的 不能画出一个标准圆形  或者我这么问 一个60宽度的滑块 需要设置border_radius为多少 它是圆形  我设置120的时候是一个圆形 但是有点椭圆 不标准

**Comment by chinalwb** [comment]
看高度. 如果高度为 60dp, 设置border_radius为 30dp

**Comment by mallxiaodoudou** [comment]
[](url)
![微信图片_20201103171554](https://user-images.githubusercontent.com/23752905/97967600-6778d880-1df8-11eb-96be-ced4c7fb9980.png)
[
![微信图片_20201103171832](https://user-images.githubusercontent.com/23752905/97967777-a6a72980-1df8-11eb-94b8-9a87b448a21b.png)
](url)
我改了下代码 把滑块背景设置设置透明 滑块设置一个圆形的图片  这样就没有白色的背景覆盖过去的那种效果

**Comment by mallxiaodoudou** [comment]
听你的设置高度的一半圆角 也可以了 现在是一个标准圆了  感谢了大佬

**Comment by chinalwb** [comment]
牛逼牛逼 我还在思考你上一个 comment 是什么意思呢.

Pay Money $8.00  看起来APP 是一个比较有钱的领域. 🐂牛!
