### ISSUE TITLE
Error : Failed to resolve: com.github.chinalwb:slidetoconfirm:1.0.3

### ISSUE THREAD

**Issue by kumzi** [chinalwb/slidetoconfirm#5]
While trying to import the project, I get the following error:
Failed to resolve: com.github.chinalwb:slidetoconfirm:1.0.3

Android Studio : Android Studio Dolphin | 2021.3.1 Patch 1

**Comment by chinalwb** [comment]
It was released to bintray (jCenter). Seems like it stops servicing now. I will find a chance to migrate it to Github maven repo.

Meantime, you can checkout the source code and add it as a dependency to your project.

**Comment by kumzi** [comment]
Thank you for the response. I solved it by adding   `maven { url 'https://jitpack.io' }` in `dependencyResolutionManagement` in settings.gradle.

**Comment by chinalwb** [comment]
That's great! Thanks for the update. I didn't even know this lib has already spread to other maven repo.

**Comment by kumzi** [comment]
Could you please check and reply to the other issue I created?
