### ISSUE TITLE
Is there a possibility of animation of drawable within the button after the swipe

### ISSUE THREAD

**Issue by kumzi** [chinalwb/slidetoconfirm#6]
I need to use this on swipe I'll be performing a web call and I would to animate the drawable within the button (like loading) and then once I receive the response after the webcall, I need to change the icon and color of the button. How that could be achieved using this API?

**Comment by chinalwb** [comment]
well I don't think this is available in this lib out of box for now. maybe you can check out this one: https://github.com/cortinico/slidetoact.

**Comment by kumzi** [comment]
Thank you. I'll look into this.

**Comment by kumzi** [comment]
I looked into this and understood that there is no loading state for this API. Could you please help it add that feature (loading). If you will, I would pay you. I need to implement this as a part of my school project.

**Comment by chinalwb** [comment]
Please contact with 329055754@qq.com.

**Comment by kumzi** [comment]
I sent an email. Could you please check?
